/*CREATE USER VEM_SER  IDENTIFIED BY oracle;
GRANT CONNECT TO VEM_SER;
GRANT CONNECT, RESOURCE, DBA TO VEM_SER;
GRANT CREATE SESSION TO VEM_SER;
GRANT DBA TO VEM_SER;
GRANT CREATE VIEW, CREATE PROCEDURE, CREATE SEQUENCE to VEM_SER;
GRANT UNLIMITED TABLESPACE TO VEM_SER;
GRANT CREATE MATERIALIZED VIEW TO VEM_SER;
GRANT CREATE TABLE TO VEM_SER;
GRANT GLOBAL QUERY REWRITE TO VEM_SER;
GRANT SELECT ANY TABLE TO VEM_SER;


-- criar uma tabela
CREATE TABLE VEM_SER.PESSOA (
 id_pessoa NUMBER NOT NULL,
 nome VARCHAR2(255) NOT NULL,
 data_nascimento DATE NOT NULL,
 telefone VARCHAR2(14), -- +5551995249346
 idade NUMBER(3) NOT NULL,
 altura DECIMAL(4,2) NOT NULL,
 cpf CHAR(11) UNIQUE NOT NULL,
 PRIMARY KEY(id_pessoa)
);



--criar uma sequencia
CREATE SEQUENCE seq_pessoa
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

--DROP é o comando para excluir tanto a sequencia quanto o usuario "ex: DROP TABLE nome_da_tabela"


--Dados para incrementar a tabela 
SELECT * FROM VEM_SER.PESSOA;
SELECT ID_PESSOA
, CPF
,TELEFONE 
, NOME
FROM VEM_SER.PESSOA;

--Insert

INSERT INTO VEM_SER.PESSOA (ID_PESSOA, NOME, DATA_NASCIMENTO, TELEFONE, IDADE, ALTURA, CPF)
/*VALUES(VEM_SER.SEQ_PESSOA.nextval, 'Flávio dos Santos', TO_DATE('03-02-1992', 'dd-mm-yyyy'), '61993302535', 30, 1.85, '04590895101');
VALUES(SEQ_PESSOA.nextval, 'Maicon Machado Gerardi', TO_DATE('08-09-1991', 'dd-mm-yyyy'), '519958654566', 30, 1.75, '50799501026');*/

--==========================================================================================================================================================
--homework aula01
/*
CREATE TABLE VEM_SER.ESTUDANTE (
 id NUMBER NOT NULL,
 nome VARCHAR2(200) NOT NULL,
 data_nascimento DATE NOT NULL,
 nr_matricula VARCHAR2(10) UNIQUE NOT NULL,
 ativo char(1),
 PRIMARY KEY(id)
);

--criar uma sequencia
CREATE SEQUENCE VEM_SER.SEQ_ESTUDANTE
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;



--INSERT (inserir o nome dos alunos na tabela estudante)
INSERT INTO VEM_SER.ESTUDANTE (ID , NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.nextval, 'felipe', TO_DATE('03-02-1992', 'dd-mm-yyyy'), '1234567811', 's');
INSERT INTO VEM_SER.ESTUDANTE (ID , NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.nextval, 'paulo', TO_DATE('03-02-1992', 'dd-mm-yyyy'), '1234567822', 's');
INSERT INTO VEM_SER.ESTUDANTE (ID , NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.nextval, 'flavio', TO_DATE('03-02-1992', 'dd-mm-yyyy'), '1234567823', 's');
INSERT INTO VEM_SER.ESTUDANTE (ID , NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.nextval, 'joao', TO_DATE('03-02-1992', 'dd-mm-yyyy'), '1234567894', 's');
INSERT INTO VEM_SER.ESTUDANTE (ID , NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.nextval, 'laura', TO_DATE('03-02-1992', 'dd-mm-yyyy'), '1234567895', 's');
INSERT INTO VEM_SER.ESTUDANTE (ID , NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.nextval, 'luana', TO_DATE('03-02-1992', 'dd-mm-yyyy'), '1234567896', 's');
INSERT INTO VEM_SER.ESTUDANTE (ID , NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.nextval, 'fernando', TO_DATE('03-02-1992', 'dd-mm-yyyy'), '1234567897', 's');
INSERT INTO VEM_SER.ESTUDANTE (ID , NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.nextval, 'pedro', TO_DATE('03-02-1992', 'dd-mm-yyyy'), '1234567898', 's');
INSERT INTO VEM_SER.ESTUDANTE (ID , NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.nextval, 'mauricio', TO_DATE('03-02-1992', 'dd-mm-yyyy'), '1234567899', 's');
INSERT INTO VEM_SER.ESTUDANTE (ID , NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.nextval, 'epaminondas', TO_DATE('03-02-1992', 'dd-mm-yyyy'), '1234567890', 's');


--SELECT 
SELECT * FROM VEM_SER.ESTUDANTE;
SELECT ID
, NOME
, DATA_NASCIMENTO 
, NR_MATRICULA
, ATIVO
FROM VEM_SER.ESTUDANTE;


--DROP SEQUENCIA E TABELAS
DROP SEQUENCE SEQ_ESTUDANTE;

DROP TABLE VEM_SER.ESTUDANTE;*/

